[project]
name = "llm-tic-tac-toe"
version = "0.1.0"
description = "LLMs play tic-tac-toe"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "ollama>=0.6.0",
    "requests>=2.32.5",
]
